local STRINGS = GLOBAL.STRINGS

STRINGS.NAMES.KYNO_DRAGOONDEN = "Dragoon Den"
STRINGS.RECIPE_DESC.KYNO_DRAGOONDEN = "Enter the Dragoon's Den."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_DRAGOONDEN = "Even goons gotta sleep."

STRINGS.NAMES.KYNO_ELEPHANTCACTUS = "Elephant Cactus"
STRINGS.RECIPE_DESC.KYNO_ELEPHANTCACTUS = "Spiky!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ELEPHANTCACTUS = "That cactus seems abnormally pokey."

STRINGS.NAMES.KYNO_ROCK_OBSIDIAN = "Obsidian Boulder"
STRINGS.RECIPE_DESC.KYNO_ROCK_OBSIDIAN = "Through the Fire and Flames."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ROCK_OBSIDIAN = "It wouldn't fit in my pocket."

STRINGS.NAMES.KYNO_ROCK_CHARCOAL = "Charcoal Boulder"
STRINGS.RECIPE_DESC.KYNO_ROCK_CHARCOAL = "Ashes to the ashes."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ROCK_CHARCOAL = "A large sedimentary rock."

STRINGS.NAMES.KYNO_VOLCANO_SHRUB = "Burnt Ash Tree"
STRINGS.RECIPE_DESC.KYNO_VOLCANO_SHRUB = "A Burnt Ash Tree."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_VOLCANO_SHRUB = "I wonder what it used to be?"

STRINGS.NAMES.COFFEEBUSH = "Coffee Plant"
STRINGS.RECIPE_DESC.COFFEEBUSH = "Coffee Baby!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBUSH = "Does that bush grow... coffee beans?!"

STRINGS.NAMES.DUG_COFFEEBUSH = "Coffee Plant"
STRINGS.RECIPE_DESC.DUG_COFFEEBUSH = "Coffee Baby!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_COFFEEBUSH = "Does that bush grow... coffee beans?!"

STRINGS.NAMES.KYNO_COFFEEBEANS = "Coffee Beans"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COFFEEBEANS = "Glorious!"

STRINGS.NAMES.KYNO_COFFEEBEANS_COOKED = "Roasted Coffee Beans"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "Could use hot water...!"

STRINGS.NAMES.COFFEE = "Coffee"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEE = "Smells delicious and energizing!"

STRINGS.NAMES.KYNO_ALTAR_PILLAR = "Stone Pillar"
STRINGS.RECIPE_DESC.KYNO_ALTAR_PILLAR = "A Pillar made out of hard stone."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ALTAR_PILLAR = "It's tall."

STRINGS.NAMES.KYNO_VOLCANO_ALTAR = "Volcano Altar of Snackrifice"
STRINGS.RECIPE_DESC.KYNO_VOLCANO_ALTAR = "Beware the Power of Gods."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_VOLCANO_ALTAR = "The altar is open and ready to accept offerings!"

STRINGS.NAMES.KYNO_WORKBENCH = "Obsidian Workbench"
STRINGS.RECIPE_DESC.KYNO_WORKBENCH = "It's hot to the touch."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WORKBENCH = "Just the spot to learn volcanic craftsmanship."

-- Turfs --
STRINGS.NAMES.TURF_MAGMAFIELD = "Magma Turf"
STRINGS.RECIPE_DESC.TURF_MAGMAFIELD = "Lava-y floor."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_MAGMAFIELD = "Step stones."

STRINGS.NAMES.TURF_VOLCANO = "Volcano Turf"
STRINGS.RECIPE_DESC.TURF_VOLCANO = "Volcano-y turf."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_VOLCANO = "Step stones."

STRINGS.NAMES.TURF_VOLCANO_ROCK = "Volcano Rock Turf"
STRINGS.RECIPE_DESC.TURF_VOLCANO_ROCK = "Volcano Rock-y turf."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_VOLCANO_ROCK = "Step stones."

STRINGS.NAMES.TURF_ASH = "Ashy Turf"
STRINGS.RECIPE_DESC.TURF_ASH = "Ashy Turf."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_ASH = "It's covered with ash."

STRINGS.NAMES.KYNO_SW_CATALOGUE_BOOK = "Shipwrecked Catalogue Book"
STRINGS.RECIPE_DESC.KYNO_SW_CATALOGUE_BOOK = "Unlocks Shipwrecked Tab."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SW_CATALOGUE_BOOK = "I can craft structures from Shipwrecked with this."

STRINGS.NAMES.KYNO_SW_PROTOTYPER = "Seaworthy Replica"
STRINGS.RECIPE_DESC.KYNO_SW_PROTOTYPER = "Unlocks Shipwrecked Tab."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SW_PROTOTYPER = "I can craft structures from shipwrecked with this."

STRINGS.NAMES.KYNO_ROCK_LIMPET = "Limpet Rock"
STRINGS.RECIPE_DESC.KYNO_ROCK_LIMPET = "Covered with Limpets."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ROCK_LIMPET = "Could be used as food source in a pinch."

STRINGS.NAMES.KYNO_VINEBUSH = "Vine Bush"
STRINGS.RECIPE_DESC.KYNO_VINEBUSH = "It's all viney!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_VINEBUSH = "What a crazy looking plant."

STRINGS.NAMES.KYNO_BAMBOOTREE = "Bamboo Patch"
STRINGS.RECIPE_DESC.KYNO_BAMBOOTREE = "A stick-y shrub."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BAMBOOTREE = "Looks pretty sturdy."

STRINGS.NAMES.JUNGLETREESEED = "Jungle Tree Seed"
STRINGS.RECIPE_DESC.JUNGLETREESEED = "Wild as Jungle can be."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREESEED = "Hard to believe such a big tree comes from this!"

STRINGS.NAMES.KYNO_JUNGLETREE_SAPLING = "Jungle Tree Sapling"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_JUNGLETREE_SAPLING = "It's growing..."

STRINGS.NAMES.JUNGLETREE = "Jungle Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE = "That tree needs a hair cut."

STRINGS.NAMES.JUNGLETREE_SHORT = "Jungle Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE_SHORT = "That tree needs a hair cut."

STRINGS.NAMES.JUNGLETREE_NORMAL = "Jungle Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE_NORMAL = "That tree needs a hair cut."

STRINGS.NAMES.JUNGLETREE_TALL = "Jungle Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE_TALL = "That tree needs a hair cut."

STRINGS.NAMES.JUNGLETREE_BURNT = "Jungle Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE_BURNT = "Oops!"

STRINGS.NAMES.JUNGLETREE_STUMP = "Jungle Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE_STUMP = "Oh no."

STRINGS.NAMES.COCONUT = "Coconut"
STRINGS.RECIPE_DESC.COCONUT = "Edible Tree Sapling!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONUT = "Ay! My favorite tree fruit!"

STRINGS.NAMES.KYNO_PALMTREE_SAPLING = "Palm Tree Sapling"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PALMTREE_SAPLING = "It's growing..."

STRINGS.NAMES.PALMTREE = "Palm Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMTREE = "How luxurious."

STRINGS.NAMES.PALMTREE_SHORT = "Palm Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMTREE_SHORT = "How luxurious."

STRINGS.NAMES.PALMTREE_NORMAL = "Palm Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMTREE_NORMAL = "How luxurious."

STRINGS.NAMES.PALMTREE_TALL = "Palm Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMTREE_TALL = "How luxurious."

STRINGS.NAMES.PALMTREE_BURNT = "Palm Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMTREE_BURNT = "Oops!"

STRINGS.NAMES.PALMTREE_STUMP = "Palm Tree" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMTREE_STUMP = "Oh no."

STRINGS.NAMES.KYNO_SANDHILL = "Sandy Pile"
STRINGS.RECIPE_DESC.KYNO_SANDHILL = "A common pile of sand."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SANDHILL = "Wish I had a bucket and a shovel."

STRINGS.NAMES.SEASHELL = "Seashell"
STRINGS.RECIPE_DESC.SEASHELL = "The Sound of the Sea."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEASHELL = "Look what the tide brought in!"

STRINGS.NAMES.KYNO_SEASHELL_BURIED = "Seashell"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SEASHELL_BURIED = "Look what the tide brought in!"

STRINGS.NAMES.KYNO_DEBRIS = "Debris"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_DEBRIS = "Part of a wrecked ship."

STRINGS.NAMES.KYNO_SHIPMAST = "Debris"
STRINGS.RECIPE_DESC.KYNO_SHIPMAST = "Stupid Bird."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SHIPMAST = "Part of a wrecked ship."

STRINGS.NAMES.KYNO_WALLY_BIRD = "Debris"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WALLY_BIRD = "Part of a wrecked ship."

STRINGS.NAMES.KYNO_DEBRIS_1 = "Debris"
STRINGS.RECIPE_DESC.KYNO_DEBRIS_1 = "It's a bunch of Debris."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_DEBRIS_1 = "Part of a wrecked ship."

STRINGS.NAMES.KYNO_DEBRIS_2 = "Debris"
STRINGS.RECIPE_DESC.KYNO_DEBRIS_2 = "It's a bunch of Debris."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_DEBRIS_2 = "Part of a wrecked ship."

STRINGS.NAMES.KYNO_DEBRIS_3 = "Debris"
STRINGS.RECIPE_DESC.KYNO_DEBRIS_3 = "It's a bunch of Debris."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_DEBRIS_3 = "Part of a wrecked ship."

STRINGS.NAMES.KYNO_CRATE = "Crate"
STRINGS.RECIPE_DESC.KYNO_CRATE = "A Wooden Crate."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CRATE = "There must be a way to open it."

STRINGS.NAMES.KYNO_LIVING_JUNGLETREE = "Regular Jungle Tree"
STRINGS.RECIPE_DESC.KYNO_LIVING_JUNGLETREE = "A living jungle tree."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_LIVING_JUNGLETREE = "There's something odd about this tree."

STRINGS.NAMES.KYNO_MAGMAROCK_GOLD = "Magma Pile"
STRINGS.RECIPE_DESC.KYNO_MAGMAROCK_GOLD = "Magma-nificent!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MAGMAROCK_GOLD = "Well, it's a rock."

STRINGS.NAMES.KYNO_MAGMAROCK = "Magma Pile"
STRINGS.RECIPE_DESC.KYNO_MAGMAROCK = "Magma-nificent!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MAGMAROCK = "Well, it's a rock."

STRINGS.NAMES.KYNO_PRIMEAPE_BARREL = "Prime Ape Hut"
STRINGS.RECIPE_DESC.KYNO_PRIMEAPE_BARREL = "More monkeys!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PRIMEAPE_BARREL = "Here be evil."

STRINGS.NAMES.KYNO_SHARKITTENDEN = "Sharkitten Den"
STRINGS.RECIPE_DESC.KYNO_SHARKITTENDEN = "Shark home!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SHARKITTENDEN = "I smell... kitty litter?"

STRINGS.NAMES.KYNO_SWEET_POTATO_PLANTED = "Sweet Potato"
STRINGS.RECIPE_DESC.KYNO_SWEET_POTATO_PLANTED = "Sweet Sweet Potato."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SWEET_POTATO_PLANTED = "Looks yammy!"

STRINGS.NAMES.KYNO_MERMHUT = "Mermhouse"
STRINGS.RECIPE_DESC.KYNO_MERMHUT = "A Tropical Merm Hut."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MERMHUT = "They copied the pigs, but they're even less intelligent."

STRINGS.NAMES.KYNO_FISHERMERMHUT = "Fishermerm's Hut"
STRINGS.RECIPE_DESC.KYNO_FISHERMERMHUT = "A Tropical Fisher's Hut."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_FISHERMERMHUT = "Doesn't smell very good."

STRINGS.NAMES.KYNO_TIDALPOOL_SMALL = "Small Tidal Pool"
STRINGS.RECIPE_DESC.KYNO_TIDALPOOL_SMALL = "A small tropical pond."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TIDALPOOL_SMALL = "Seems like a popular hangout spot for fishes."

STRINGS.NAMES.KYNO_TIDALPOOL_MEDIUM = "Medium Tidal Pool"
STRINGS.RECIPE_DESC.KYNO_TIDALPOOL_MEDIUM = "A medium tropical pond."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TIDALPOOL_MEDIUM = "Seems like a popular hangout spot for fishes."

STRINGS.NAMES.KYNO_TIDALPOOL_BIG = "Large Tidal Pool"
STRINGS.RECIPE_DESC.KYNO_TIDALPOOL_BIG = "A large tropical pond."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TIDALPOOL_BIG = "Seems like a popular hangout spot for fishes."

STRINGS.NAMES.KYNO_MARSH_PLANT_TROPICAL = "Plant"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MARSH_PLANT_TROPICAL = "It's a plant."

STRINGS.NAMES.KYNO_POISONHOLE = "Poisonous Hole"
STRINGS.RECIPE_DESC.KYNO_POISONHOLE = "Toxic like you."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_POISONHOLE = "I think I'll stay away from that."

STRINGS.NAMES.KYNO_SLOTMACHINE  = "Slot Machine"
STRINGS.RECIPE_DESC.KYNO_SLOTMACHINE = "The Cassino is disabled."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SLOTMACHINE = "Give my money back, now!"

STRINGS.NAMES.KYNO_WILDBORE_HOUSE = "Wildbore House"
STRINGS.RECIPE_DESC.KYNO_WILDBORE_HOUSE = "Pig out!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WILDBORE_HOUSE = "What a bore-ing house."

STRINGS.NAMES.KYNO_WILDBORE_HEAD = "Wildbore Head"
STRINGS.RECIPE_DESC.KYNO_WILDBORE_HEAD = "The remains of a war."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WILDBORE_HEAD = "Very gross!"

STRINGS.NAMES.KYNO_CHIMINEA = "Chiminea"
STRINGS.RECIPE_DESC.KYNO_CHIMINEA = "Fire and wind don't mix."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CHIMINEA = "Take that, wind!"

STRINGS.NAMES.KYNO_OBSIDIAN_FIREPIT = "Obsidian Fire Pit"
STRINGS.RECIPE_DESC.KYNO_OBSIDIAN_FIREPIT = "The fieriest of all fires!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_OBSIDIAN_FIREPIT = "This fire pit is a conductor for even more... fire."

STRINGS.NAMES.KYNO_PALMLEAF_HUT = "Palm Leaf Hut"
STRINGS.RECIPE_DESC.KYNO_PALMLEAF_HUT = "Escape the rain. Mostly."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PALMLEAF_HUT = "Shade, sweet shade."

STRINGS.NAMES.KYNO_DOYDOY_NEST = "Doydoy Nest"
STRINGS.RECIPE_DESC.KYNO_DOYDOY_NEST = "Just doy it."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_DOYDOY_NEST = "Those filthy birds breed here."

STRINGS.NAMES.KYNO_ICEMAKER = "Ice Maker 3000"
STRINGS.RECIPE_DESC.KYNO_ICEMAKER = "Ice, ice, baby!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ICEMAKER = "It's running great!"

STRINGS.NAMES.KYNO_SANDCASTLE = "Sand Castle"
STRINGS.RECIPE_DESC.KYNO_SANDCASTLE = "Therapeutic and relaxing."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SANDCASTLE = "Who knew sand could look so good."

STRINGS.NAMES.KYNO_PIRATIHATITATOR = "Piratihatitator"
STRINGS.RECIPE_DESC.KYNO_PIRATIHATITATOR = "Make your pirate hat... magic."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIRATIHATITATOR = "It's twisting my tongue."