local STRINGS = GLOBAL.STRINGS

STRINGS.NAMES.KYNO_DRAGOONDEN = "Dragoon Den"
STRINGS.RECIPE_DESC.KYNO_DRAGOONDEN = "Enter the Dragoon's Den."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_DRAGOONDEN = "Even goons gotta sleep."

STRINGS.NAMES.KYNO_ELEPHANTCACTUS = "Elephant Cactus"
STRINGS.RECIPE_DESC.KYNO_ELEPHANTCACTUS = "Spiky!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ELEPHANTCACTUS = "That cactus seems abnormally pokey."

STRINGS.NAMES.KYNO_ROCK_OBSIDIAN = "Obsidian Boulder"
STRINGS.RECIPE_DESC.KYNO_ROCK_OBSIDIAN = "Through the Fire and Flames."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ROCK_OBSIDIAN = "It wouldn't fit in my pocket."

STRINGS.NAMES.KYNO_ROCK_CHARCOAL = "Charcoal Boulder"
STRINGS.RECIPE_DESC.KYNO_ROCK_CHARCOAL = "Ashes to the ashes."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ROCK_CHARCOAL = "A large sedimentary rock."

STRINGS.NAMES.KYNO_VOLCANO_SHRUB = "Burnt Ash Tree"
STRINGS.RECIPE_DESC.KYNO_VOLCANO_SHRUB = "A Burnt Ash Tree."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_VOLCANO_SHRUB = "I wonder what it used to be?"

STRINGS.NAMES.COFFEEBUSH = "Coffee Plant"
STRINGS.RECIPE_DESC.COFFEEBUSH = "Coffee Baby!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBUSH = "Does that bush grow... coffee beans?!"

STRINGS.NAMES.DUG_COFFEEBUSH = "Coffee Plant"
STRINGS.RECIPE_DESC.DUG_COFFEEBUSH = "Coffee Baby!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_COFFEEBUSH = "Does that bush grow... coffee beans?!"

STRINGS.NAMES.KYNO_COFFEEBEANS = "Coffee Beans"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COFFEEBEANS = "Glorious!"

STRINGS.NAMES.KYNO_COFFEEBEANS_COOKED = "Roasted Coffee Beans"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "Could use hot water...!"

STRINGS.NAMES.COFFEE = "Coffee"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEE = "Smells delicious and energizing!"

STRINGS.NAMES.KYNO_ALTAR_PILLAR = "Stone Pillar"
STRINGS.RECIPE_DESC.KYNO_ALTAR_PILLAR = "A Pillar made out of hard stone."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ALTAR_PILLAR = "It's tall."

STRINGS.NAMES.KYNO_VOLCANO_ALTAR = "Volcano Altar of Snackrifice"
STRINGS.RECIPE_DESC.KYNO_VOLCANO_ALTAR = "Beware the Power of Gods."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_VOLCANO_ALTAR = "The altar is open and ready to accept offerings!"

STRINGS.NAMES.KYNO_WORKBENCH = "Obsidian Workbench"
STRINGS.RECIPE_DESC.KYNO_WORKBENCH = "It's hot to the touch."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WORKBENCH = "Just the spot to learn volcanic craftsmanship."

-- Turfs --
STRINGS.NAMES.TURF_MAGMAFIELD = "Magma Turf"
STRINGS.RECIPE_DESC.TURF_MAGMAFIELD = "Lava-y floor."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_MAGMAFIELD = "Step stones."

STRINGS.NAMES.TURF_VOLCANO = "Volcano Turf"
STRINGS.RECIPE_DESC.TURF_VOLCANO = "Volcano-y turf."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_VOLCANO = "Step stones."

STRINGS.NAMES.TURF_VOLCANO_ROCK = "Volcano Rock Turf"
STRINGS.RECIPE_DESC.TURF_VOLCANO_ROCK = "Volcano Rock-y turf."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_VOLCANO_ROCK = "Step stones."

STRINGS.NAMES.TURF_ASH = "Ashy Turf"
STRINGS.RECIPE_DESC.TURF_ASH = "Ashy Turf."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_ASH = "It's covered with ash."

STRINGS.NAMES.TURF_BEACH = "Beach Turf"
STRINGS.RECIPE_DESC.TURF_BEACH = "Copacabana feelings."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_BEACH = "Beach time!"

STRINGS.NAMES.TURF_MEADOW = "Meadow Turf"
STRINGS.RECIPE_DESC.TURF_MEADOW = "Meadow-y Turf."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_MEADOW = "It's very green."

STRINGS.NAMES.TURF_JUNGLE = "Jungle Turf"
STRINGS.RECIPE_DESC.TURF_JUNGLE = "Welcome to the jungle!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_JUNGLE = "Wild as jungle can be."

STRINGS.NAMES.TURF_SNAKESKINFLOOR = "Snakeskin Rug"
STRINGS.RECIPE_DESC.TURF_SNAKESKINFLOOR = "Really ties the room together."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_SNAKESKINFLOOR = "Ssssstyle!"

STRINGS.NAMES.TURF_TIDALMARSH = "Tidal Marsh Turf"
STRINGS.RECIPE_DESC.TURF_TIDALMARSH = "Marsh-y floor."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_TIDALMARSH = "It's like a brown swamp."
-- -- 

STRINGS.NAMES.KYNO_SW_CATALOGUE_BOOK = "Shipwrecked Catalogue Book"
STRINGS.RECIPE_DESC.KYNO_SW_CATALOGUE_BOOK = "Unlocks Shipwrecked Tab."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SW_CATALOGUE_BOOK = "I can craft structures from Shipwrecked with this."

STRINGS.NAMES.KYNO_SW_PROTOTYPER = "Seaworthy"
STRINGS.RECIPE_DESC.KYNO_SW_PROTOTYPER = "Teleport south for the winter."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SW_PROTOTYPER = "And so, I sail away into the horizon!"

STRINGS.NAMES.KYNO_ROCK_LIMPET = "Limpet Rock"
STRINGS.RECIPE_DESC.KYNO_ROCK_LIMPET = "Covered with Limpets."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ROCK_LIMPET = "Could be used as food source in a pinch."

STRINGS.NAMES.KYNO_VINEBUSH = "Vine Bush"
STRINGS.RECIPE_DESC.KYNO_VINEBUSH = "It's all viney!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_VINEBUSH = "What a crazy looking plant."

STRINGS.NAMES.KYNO_BAMBOOTREE = "Bamboo Patch"
STRINGS.RECIPE_DESC.KYNO_BAMBOOTREE = "A stick-y shrub."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BAMBOOTREE = "Looks pretty sturdy."

STRINGS.NAMES.JUNGLETREESEED = "Jungle Tree Seed"
STRINGS.RECIPE_DESC.JUNGLETREESEED = "Wild as Jungle can be."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREESEED = "Hard to believe such a big tree comes from this!"

STRINGS.NAMES.KYNO_JUNGLETREE_SAPLING = "Jungle Tree Sapling"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_JUNGLETREE_SAPLING = "It's growing..."

STRINGS.NAMES.JUNGLETREE = "Jungle Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE = "That tree needs a hair cut."

STRINGS.NAMES.JUNGLETREE_SHORT = "Jungle Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE_SHORT = "That tree needs a hair cut."

STRINGS.NAMES.JUNGLETREE_NORMAL = "Jungle Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE_NORMAL = "That tree needs a hair cut."

STRINGS.NAMES.JUNGLETREE_TALL = "Jungle Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE_TALL = "That tree needs a hair cut."

STRINGS.NAMES.JUNGLETREE_BURNT = "Jungle Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE_BURNT = "Oops!"

STRINGS.NAMES.JUNGLETREE_STUMP = "Jungle Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUNGLETREE_STUMP = "Oh no."

STRINGS.NAMES.COCONUT = "Coconut"
STRINGS.RECIPE_DESC.COCONUT = "Edible Tree Sapling!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONUT = "Ay! My favorite tree fruit!"

STRINGS.NAMES.KYNO_PALMTREE_SAPLING = "Palm Tree Sapling"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PALMTREE_SAPLING = "It's growing..."

STRINGS.NAMES.PALMTREE = "Palm Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMTREE = "How luxurious."

STRINGS.NAMES.PALMTREE_SHORT = "Palm Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMTREE_SHORT = "How luxurious."

STRINGS.NAMES.PALMTREE_NORMAL = "Palm Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMTREE_NORMAL = "How luxurious."

STRINGS.NAMES.PALMTREE_TALL = "Palm Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMTREE_TALL = "How luxurious."

STRINGS.NAMES.PALMTREE_BURNT = "Palm Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMTREE_BURNT = "Oops!"

STRINGS.NAMES.PALMTREE_STUMP = "Palm Tree" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALMTREE_STUMP = "Oh no."

STRINGS.NAMES.KYNO_SANDHILL = "Sandy Pile"
STRINGS.RECIPE_DESC.KYNO_SANDHILL = "A common pile of sand."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SANDHILL = "Wish I had a bucket and a shovel."

STRINGS.NAMES.SEASHELL = "Seashell"
STRINGS.RECIPE_DESC.SEASHELL = "The Sound of the Sea."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEASHELL = "Look what the tide brought in!"

STRINGS.NAMES.KYNO_SEASHELL_BURIED = "Seashell"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SEASHELL_BURIED = "Look what the tide brought in!"

STRINGS.NAMES.KYNO_DEBRIS = "Debris"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_DEBRIS = "Part of a wrecked ship."

STRINGS.NAMES.KYNO_SHIPMAST = "Debris"
STRINGS.RECIPE_DESC.KYNO_SHIPMAST = "Stupid Bird."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SHIPMAST = "Part of a wrecked ship."

STRINGS.NAMES.KYNO_WALLY_BIRD = "Debris"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WALLY_BIRD = "Part of a wrecked ship."

STRINGS.NAMES.KYNO_DEBRIS_1 = "Debris"
STRINGS.RECIPE_DESC.KYNO_DEBRIS_1 = "It's a bunch of Debris."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_DEBRIS_1 = "Part of a wrecked ship."

STRINGS.NAMES.KYNO_DEBRIS_2 = "Debris"
STRINGS.RECIPE_DESC.KYNO_DEBRIS_2 = "It's a bunch of Debris."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_DEBRIS_2 = "Part of a wrecked ship."

STRINGS.NAMES.KYNO_DEBRIS_3 = "Debris"
STRINGS.RECIPE_DESC.KYNO_DEBRIS_3 = "It's a bunch of Debris."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_DEBRIS_3 = "Part of a wrecked ship."

STRINGS.NAMES.KYNO_CRATE = "Crate"
STRINGS.RECIPE_DESC.KYNO_CRATE = "A Wooden Crate."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CRATE = "There must be a way to open it."

STRINGS.NAMES.KYNO_LIVING_JUNGLETREE = "Regular Jungle Tree"
STRINGS.RECIPE_DESC.KYNO_LIVING_JUNGLETREE = "A living jungle tree."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_LIVING_JUNGLETREE = "There's something odd about this tree."

STRINGS.NAMES.KYNO_MAGMAROCK_GOLD = "Magma Pile"
STRINGS.RECIPE_DESC.KYNO_MAGMAROCK_GOLD = "Magma-nificent!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MAGMAROCK_GOLD = "Well, it's a rock."

STRINGS.NAMES.KYNO_MAGMAROCK = "Magma Pile"
STRINGS.RECIPE_DESC.KYNO_MAGMAROCK = "Magma-nificent!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MAGMAROCK = "Well, it's a rock."

STRINGS.NAMES.KYNO_PRIMEAPE_BARREL = "Prime Ape Hut"
STRINGS.RECIPE_DESC.KYNO_PRIMEAPE_BARREL = "More monkeys!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PRIMEAPE_BARREL = "Here be evil."

STRINGS.NAMES.KYNO_SHARKITTENDEN = "Sharkitten Den"
STRINGS.RECIPE_DESC.KYNO_SHARKITTENDEN = "Shark in the house!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SHARKITTENDEN = "I smell... kitty litter?"

STRINGS.NAMES.KYNO_SWEET_POTATO_PLANTED = "Sweet Potato"
STRINGS.RECIPE_DESC.KYNO_SWEET_POTATO_PLANTED = "Sweet Sweet Potato."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SWEET_POTATO_PLANTED = "Looks yammy!"

STRINGS.NAMES.KYNO_MERMHUT = "Mermhouse"
STRINGS.RECIPE_DESC.KYNO_MERMHUT = "A Tropical Merm Hut."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MERMHUT = "They copied the pigs, but they're even less intelligent."

STRINGS.NAMES.KYNO_FISHERMERMHUT = "Fishermerm's Hut"
STRINGS.RECIPE_DESC.KYNO_FISHERMERMHUT = "A Tropical Fisher's Hut."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_FISHERMERMHUT = "Doesn't smell very good."

STRINGS.NAMES.KYNO_TIDALPOOL_SMALL = "Small Tidal Pool"
STRINGS.RECIPE_DESC.KYNO_TIDALPOOL_SMALL = "A small tropical pond."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TIDALPOOL_SMALL = "Seems like a popular hangout spot for fishes."

STRINGS.NAMES.KYNO_TIDALPOOL_MEDIUM = "Medium Tidal Pool"
STRINGS.RECIPE_DESC.KYNO_TIDALPOOL_MEDIUM = "A medium tropical pond."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TIDALPOOL_MEDIUM = "Seems like a popular hangout spot for fishes."

STRINGS.NAMES.KYNO_TIDALPOOL_BIG = "Large Tidal Pool"
STRINGS.RECIPE_DESC.KYNO_TIDALPOOL_BIG = "A large tropical pond."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TIDALPOOL_BIG = "Seems like a popular hangout spot for fishes."

STRINGS.NAMES.KYNO_MARSH_PLANT_TROPICAL = "Plant"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MARSH_PLANT_TROPICAL = "It's a plant."

STRINGS.NAMES.KYNO_POISONHOLE = "Poisonous Hole"
STRINGS.RECIPE_DESC.KYNO_POISONHOLE = "Toxic like you."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_POISONHOLE = "I think I'll stay away from that."

STRINGS.NAMES.KYNO_SLOTMACHINE  = "Slot Machine"
STRINGS.RECIPE_DESC.KYNO_SLOTMACHINE = "The Cassino is disabled."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SLOTMACHINE = "Give my money back, now!"

STRINGS.NAMES.KYNO_WILDBORE_HOUSE = "Wildbore House"
STRINGS.RECIPE_DESC.KYNO_WILDBORE_HOUSE = "Pig out!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WILDBORE_HOUSE = "What a bore-ing house."

STRINGS.NAMES.KYNO_WILDBORE_HEAD = "Wildbore Head"
STRINGS.RECIPE_DESC.KYNO_WILDBORE_HEAD = "The remains of a war."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WILDBORE_HEAD = "Very gross!"

STRINGS.NAMES.KYNO_CHIMINEA = "Chiminea"
STRINGS.RECIPE_DESC.KYNO_CHIMINEA = "Fire and wind don't mix."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CHIMINEA = "Take that, wind!"

STRINGS.NAMES.KYNO_OBSIDIAN_FIREPIT = "Obsidian Fire Pit"
STRINGS.RECIPE_DESC.KYNO_OBSIDIAN_FIREPIT = "The fieriest of all fires!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_OBSIDIAN_FIREPIT = "This fire pit is a conductor for even more... fire."

STRINGS.NAMES.KYNO_PALMLEAF_HUT = "Palm Leaf Hut"
STRINGS.RECIPE_DESC.KYNO_PALMLEAF_HUT = "Escape the rain. Mostly."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PALMLEAF_HUT = "Shade, sweet shade."

STRINGS.NAMES.KYNO_DOYDOY_NEST = "Doydoy Nest"
STRINGS.RECIPE_DESC.KYNO_DOYDOY_NEST = "Just doy it."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_DOYDOY_NEST = "Those filthy birds breed here."

STRINGS.NAMES.KYNO_ICEMAKER = "Ice Maker 3000"
STRINGS.RECIPE_DESC.KYNO_ICEMAKER = "Ice, ice, baby!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ICEMAKER = "It's running great!"

STRINGS.NAMES.KYNO_SANDCASTLE = "Sand Castle"
STRINGS.RECIPE_DESC.KYNO_SANDCASTLE = "Therapeutic and relaxing."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SANDCASTLE = "Who knew sand could look so good."

STRINGS.NAMES.KYNO_PIRATIHATITATOR = "Piratihatitator"
STRINGS.RECIPE_DESC.KYNO_PIRATIHATITATOR = "Make your pirate hat... magic."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIRATIHATITATOR = "It's twisting my tongue."

STRINGS.NAMES.KYNO_SANDBAGSMALL_ITEM = "Sandbag"
STRINGS.RECIPE_DESC.KYNO_SANDBAGSMALL_ITEM = "Floodproof."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SANDBAGSMALL_ITEM = "Keeps water at bay."

STRINGS.NAMES.KYNO_SANDBAGSMALL = "Sandbag"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SANDBAGSMALL = "Keeps the water at bay."

STRINGS.NAMES.MANGROVETREE = "Mangrove Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MANGROVETREE = "I wonder if it's getting enough water?"

STRINGS.NAMES.MANGROVETREE_STUMP = "Mangrove Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MANGROVETREE_STUMP = "Oh no!"

STRINGS.NAMES.MANGROVETREE_BURNT = "Mangrove Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MANGROVETREE_BURNT = "Oops."

STRINGS.NAMES.MANGROVETREE_SHORT = "Mangrove Tree"
STRINGS.RECIPE_DESC.MANGROVETREE_SHORT = "Tree on water!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MANGROVETREE_SHORT = "I wonder if it's getting enough water?"

STRINGS.NAMES.MANGROVETREE_NORMAL = "Mangrove Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MANGROVETREE_NORMAL = "I wonder if it's getting enough water?"

STRINGS.NAMES.MANGROVETREE_TALL = "Mangrove Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MANGROVETREE_TALL = "I wonder if it's getting enough water?"

STRINGS.NAMES.KYNO_WRECK_1 = "Wreck"
STRINGS.RECIPE_DESC.KYNO_WRECK_1 = "An old wrecked ship."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WRECK_1 = "Poor little boat."

STRINGS.NAMES.KYNO_WRECK_2 = "Wreck"
STRINGS.RECIPE_DESC.KYNO_WRECK_2 = "An old wrecked ship."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WRECK_2 = "Poor little boat."

STRINGS.NAMES.KYNO_WRECK_3 = "Wreck"
STRINGS.RECIPE_DESC.KYNO_WRECK_3 = "An old wrecked ship."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WRECK_3 = "Poor little boat."

STRINGS.NAMES.KYNO_WRECK_4 = "Wreck"
STRINGS.RECIPE_DESC.KYNO_WRECK_4 = "An old wrecked ship."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WRECK_4 = "Poor little boat."

STRINGS.NAMES.KYNO_SEAWEED = "Seaweed"
STRINGS.RECIPE_DESC.KYNO_SEAWEED = "Aquatic Plant."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SEAWEED = "A weed. Of the sea."

STRINGS.NAMES.KYNO_BRAIN_ROCK = "Brainy Sprout"
STRINGS.RECIPE_DESC.KYNO_BRAIN_ROCK = "It's a brain!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BRAIN_ROCK = "That's one smart-looking plant."

STRINGS.NAMES.WALL_LIMESTONE_ITEM = "Limestone Wall"
STRINGS.RECIPE_DESC.WALL_LIMESTONE_ITEM = "Strong wall segments."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_LIMESTONE_ITEM = "A wall made of living coral."

STRINGS.NAMES.WALL_LIMESTONE = "Limestone Wall"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_LIMESTONE = "A wall made of living coral."

STRINGS.NAMES.WALL_ENFORCEDLIMESTONE_ITEM = "Sea Wall"
STRINGS.RECIPE_DESC.WALL_ENFORCEDLIMESTONE_ITEM = "Strong wall segments to build at sea."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_ENFORCEDLIMESTONE_ITEM = "I have to build it in the water."

STRINGS.NAMES.WALL_ENFORCEDLIMESTONE = "Sea Wall"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_ENFORCEDLIMESTONE = "I have to build it in the water."

STRINGS.NAMES.KYNO_ROCK_CORAL_1 = "Coral Reef"
STRINGS.RECIPE_DESC.KYNO_ROCK_CORAL_1 = "Corals at sea!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ROCK_CORAL_1 = "I wish I had a snorkel."

STRINGS.NAMES.KYNO_ROCK_CORAL_2 = "Coral Reef"
STRINGS.RECIPE_DESC.KYNO_ROCK_CORAL_2 = "Corals at sea!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ROCK_CORAL_2 = "I wish I had a snorkel."

STRINGS.NAMES.KYNO_ROCK_CORAL_3 = "Coral Reef"
STRINGS.RECIPE_DESC.KYNO_ROCK_CORAL_3 = "Corals at sea!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ROCK_CORAL_3 = "I wish I had a snorkel."

STRINGS.NAMES.KYNO_REDBARREL = "Gunpowder Barrel"
STRINGS.RECIPE_DESC.KYNO_REDBARREL = "Deadly."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_REDBARREL = "That look dangerous."

STRINGS.NAMES.KYNO_BERMUDATRIANGLE = "Electric Isosceles"
STRINGS.RECIPE_DESC.KYNO_BERMUDATRIANGLE = "Bermudas!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BERMUDATRIANGLE = "I don't believe in mysterious occurrences."

STRINGS.NAMES.KYNO_BALLPHINHOUSE = "Ballphin Palace"
STRINGS.RECIPE_DESC.KYNO_BALLPHINHOUSE = "EeEe! EeEe!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BALLPHINHOUSE = "The place where ballphins roost."

STRINGS.NAMES.KYNO_OCTOPUSKING = "Yaarctopus"
STRINGS.RECIPE_DESC.KYNO_OCTOPUSKING = "Yar! Yar!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_OCTOPUSKING = "He's the center of this ecosystem."

STRINGS.NAMES.KYNO_LUGGAGECHEST = "Steamer Trunk"
STRINGS.RECIPE_DESC.KYNO_LUGGAGECHEST = "A dapper item storage."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_LUGGAGECHEST = "It looks like a premier steamer trunk."

STRINGS.NAMES.KYNO_FISHINHOLE = "Shoal"
STRINGS.RECIPE_DESC.KYNO_FISHINHOLE = "A natural fishin-spot!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_FISHINHOLE = "This area seems pretty fishy."

STRINGS.NAMES.KYNO_BUOY = "Buoy"
STRINGS.RECIPE_DESC.KYNO_BUOY = "Mark your place in the water."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BUOY = "Awww Yaaaa Buoy!"

STRINGS.NAMES.KYNO_SEA_CHIMINEA = "Buoyant Chiminea"
STRINGS.RECIPE_DESC.KYNO_SEA_CHIMINEA = "Fire that floats!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SEA_CHIMINEA = "Burn the sea!"

STRINGS.NAMES.KYNO_SEAYARD = "Sea Yard"
STRINGS.RECIPE_DESC.KYNO_SEAYARD = "Keep your boats ship-shape!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SEAYARD = "For keeping my ships in tiptop shape!"

STRINGS.NAMES.KYNO_EXTRACTOR = "Tar Extractor"
STRINGS.RECIPE_DESC.KYNO_EXTRACTOR = "This offshore rig knows the drill."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_EXTRACTOR = "It's running smoothly."

STRINGS.NAMES.KYNO_MUSSELFARM = "Mussels Stick"
STRINGS.RECIPE_DESC.KYNO_MUSSELFARM = "Mussels stick to it!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MUSSELFARM = "I wonder if they are from Brussels."

STRINGS.NAMES.KYNO_FISHFARM = "Fish Farm"
STRINGS.RECIPE_DESC.KYNO_FISHFARM = "Grow your own fishfood with roe!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_FISHFARM = "I gotta put something in there to grow fish."

STRINGS.NAMES.KYNO_SEALAB = "Sea Lab"
STRINGS.RECIPE_DESC.KYNO_SEALAB = "Unlock crafting recipes... at sea!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SEALAB = "For sea science!"

STRINGS.NAMES.KYNO_BURIEDTREASURE = "X Marks The Spot"
STRINGS.RECIPE_DESC.KYNO_BURIEDTREASURE = "It's a surprise to everyone."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BURIEDTREASURE = "Treasures!"

STRINGS.NAMES.KYNO_GEYSER = "Krissure"
STRINGS.RECIPE_DESC.KYNO_GEYSER = "Lava geyser!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_GEYSER = "Maybe I should stand back."

STRINGS.NAMES.KYNO_LAVAPOOL = "Lava Pool"
STRINGS.RECIPE_DESC.KYNO_LAVAPOOL = "Hot! hot! hot!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_LAVAPOOL = "Volcanic fire."

STRINGS.NAMES.KYNO_DRAGOONEGG = "Dragoon Egg"
STRINGS.RECIPE_DESC.KYNO_DRAGOONEGG = "This is a huge egg for sure."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_DRAGOONEGG = "Do I hear cracking?"

STRINGS.NAMES.KYNO_KRAKENCHEST = "Chest of the Depths"
STRINGS.RECIPE_DESC.KYNO_KRAKENCHEST = "From the deep ocean."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_KRAKENCHEST = "Cool. A big chest of a Kraken."

STRINGS.NAMES.KYNO_WATERCHEST = "Sea Chest"
STRINGS.RECIPE_DESC.KYNO_WATERCHEST = "Davy Jones' storage locker."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WATERCHEST = "I keep all my best stuff in there."

STRINGS.NAMES.KYNO_WATERCRATE = "Watery Grave"
STRINGS.RECIPE_DESC.KYNO_WATERCRATE = "A water crate."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WATERCRATE = "I hope to never end up in one of those."

STRINGS.NAMES.KYNO_WOODLEGS_CAGE = "Woodlegs' Cage"
STRINGS.RECIPE_DESC.KYNO_WOODLEGS_CAGE = "Poor pirate."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WOODLEGS_CAGE = "How did you get in there, scruffy sir?"

STRINGS.NAMES.KYNO_TARTRAP = "Tar Trap"
STRINGS.RECIPE_DESC.KYNO_TARTRAP = "Slow your enemies and you."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TARTRAP = "Sticky."

STRINGS.NAMES.KYNO_TARPIT = "Tar Slick"
STRINGS.RECIPE_DESC.KYNO_TARPIT = "The source of fuel."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TARPIT = "It's bubbling."

STRINGS.NAMES.KYNO_CAVECLEFT = "Cave Cleft"
STRINGS.RECIPE_DESC.KYNO_CAVECLEFT = "Full of bats."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CAVECLEFT = "A den of bloodsuckers."

STRINGS.NAMES.KYNO_HAM_PROTOTYPER = "Skyworthy"
STRINGS.RECIPE_DESC.KYNO_HAM_PROTOTYPER = "What could possibly go wrong?"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_HAM_PROTOTYPER = "It's a flying machine!"

STRINGS.NAMES.KYNO_PIGRUINSSMALL = "Ruinous Entrance"
STRINGS.RECIPE_DESC.KYNO_PIGRUINSSMALL = "Adventure waits!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGRUINSSMALL = "Something to explore."

STRINGS.NAMES.KYNO_PIGRUINS1 = "Ruinous Entrance"
STRINGS.RECIPE_DESC.KYNO_PIGRUINS1 = "Adventure waits!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGRUINS1 = "Something to explore."

STRINGS.NAMES.KYNO_PIGRUINS2 = "Ruinous Entrance"
STRINGS.RECIPE_DESC.KYNO_PIGRUINS2 = "Adventure waits!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGRUINS2 = "Something to explore."

STRINGS.NAMES.KYNO_PIGRUINS3 = "Ruinous Entrance"
STRINGS.RECIPE_DESC.KYNO_PIGRUINS3 = "Adventure waits!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGRUINS3 = "Something to explore."

STRINGS.NAMES.KYNO_PIGRUINS4 = "Ruinous Entrance"
STRINGS.RECIPE_DESC.KYNO_PIGRUINS4 = "Adventure waits!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGRUINS4 = "Something to explore."

STRINGS.NAMES.KYNO_PIGRUINS5 = "Ruinous Entrance"
STRINGS.RECIPE_DESC.KYNO_PIGRUINS5 = "Adventure waits!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGRUINS5 = "Something to explore."

STRINGS.NAMES.KYNO_MANTHILL = "Mant Hill"
STRINGS.RECIPE_DESC.KYNO_MANTHILL = "Giant bugs lair."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MANTHILL = "This must be where those giant bugs live."

STRINGS.NAMES.KYNO_MANTQUEENHILL = "Queen Womant Hill"
STRINGS.RECIPE_DESC.KYNO_MANTQUEENHILL = "Queen's Lair."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MANTQUEENHILL = "I hear something growling around in there."

STRINGS.NAMES.KYNO_PIGSHOP_SPA = "Curly Tails Mud Spa"
STRINGS.RECIPE_DESC.KYNO_PIGSHOP_SPA = "The mud really cleans the spores."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGSHOP_SPA = "I could use a fix-me-up."

STRINGS.NAMES.KYNO_PIGSHOP_FLOWER = "Miss Sow's Floral Arrangements"
STRINGS.RECIPE_DESC.KYNO_PIGSHOP_FLOWER = "There's a little green thum in everyone."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGSHOP_FLOWER = "This shop trades in local flora."

STRINGS.NAMES.KYNO_PIGSHOP_GENERAL = "Pigg and Pigglet's General Store"
STRINGS.RECIPE_DESC.KYNO_PIGSHOP_GENERAL = "For all your handy needs."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGSHOP_GENERAL = "A common store full of common goods."

STRINGS.NAMES.KYNO_PIGSHOP_DELI = "The Sterling Trough Deli"
STRINGS.RECIPE_DESC.KYNO_PIGSHOP_DELI = "We need more good plates to eat."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGSHOP_DELI = "A place to eat."

STRINGS.NAMES.KYNO_PIGSHOP_PRODUCE = "Swinesbury Fine Grocer's"
STRINGS.RECIPE_DESC.KYNO_PIGSHOP_PRODUCE = "Shop smart."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGSHOP_PRODUCE = "There's fresh produce in there."

STRINGS.NAMES.KYNO_PIGSHOP_ANTIQUITIES = "'The Sty' Oddities Emporium"
STRINGS.RECIPE_DESC.KYNO_PIGSHOP_ANTIQUITIES = "Where else can you get a shriveled head."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGSHOP_ANTIQUITIES = "A lot of strange things in there."

STRINGS.NAMES.KYNO_PIGSHOP_ARCANE = "The Flying Pig Arcane Shop"
STRINGS.RECIPE_DESC.KYNO_PIGSHOP_ARCANE = "For the magic half of Science and Magic."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGSHOP_ARCANE = "A shop for items of esoteric nature."

STRINGS.NAMES.KYNO_PIGSHOP_WEAPONS = "The Boar's Tusk Weapon Shop"
STRINGS.RECIPE_DESC.KYNO_PIGSHOP_WEAPONS = "All adventurers need to defend themselves."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGSHOP_WEAPONS = "Instruments of destruction."

STRINGS.NAMES.KYNO_PIGSHOP_HATSHOP = "The Sow's Hat Shop"
STRINGS.RECIPE_DESC.KYNO_PIGSHOP_HATSHOP = "All the best new fashions."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGSHOP_HATSHOP = "A place to hang your hat."

STRINGS.NAMES.KYNO_PIGSHOP_BANK = "Swinesbury Mineral Exchange"
STRINGS.RECIPE_DESC.KYNO_PIGSHOP_BANK = "Gold is a solid investment."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGSHOP_BANK = "Ah. A useful place for a change."

STRINGS.NAMES.KYNO_PIGSHOP_TINKER = "The Tinkerer's Tower"
STRINGS.RECIPE_DESC.KYNO_PIGSHOP_TINKER = "You can't think of everything."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGSHOP_TINKER = "I've been looking for something new to build."

STRINGS.NAMES.KYNO_PIGSHOP_ACADEMY = "Swinesbury Academy"
STRINGS.RECIPE_DESC.KYNO_PIGSHOP_ACADEMY = "Full of pig history."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGSHOP_ACADEMY = "I can smell the history."

STRINGS.NAMES.KYNO_PIGSHOP_CITYHALL = "Swinesbury City Hall"
STRINGS.RECIPE_DESC.KYNO_PIGSHOP_CITYHALL = "You are the mayor now."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGSHOP_CITYHALL = "The local lawmaker."

STRINGS.NAMES.KYNO_PIGTOWER3 = "Watch Tower"
STRINGS.RECIPE_DESC.KYNO_PIGTOWER3 = "Protect the citizens."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGTOWER3 = "It's surprisingly sturdy."

STRINGS.NAMES.KYNO_PIGTOWER = "Perdy Watch Tower"
STRINGS.RECIPE_DESC.KYNO_PIGTOWER = "Protect the citizens."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGTOWER = "It's surprisingly sturdy."

STRINGS.NAMES.KYNO_PIGTOWER2 = "Swinesbury Watch Tower"
STRINGS.RECIPE_DESC.KYNO_PIGTOWER2 = "Protect the citizens."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGTOWER2 = "It's surprisingly sturdy."

STRINGS.NAMES.KYNO_PIGPALACETOWER = "Palace Tower"
STRINGS.RECIPE_DESC.KYNO_PIGPALACETOWER = "Protect the queen."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGPALACETOWER = "It's surprisingly sturdy."

STRINGS.NAMES.KYNO_PIGPALACE = "Palace"
STRINGS.RECIPE_DESC.KYNO_PIGPALACE = "Where kings and queens live."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGPALACE = "Majestic."

STRINGS.NAMES.KYNO_PIGHOUSE_CITY = "Town House"
STRINGS.RECIPE_DESC.KYNO_PIGHOUSE_CITY = "Shelters one tax paying pig."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGHOUSE_CITY = "A more advanced version of pig house."

STRINGS.NAMES.KYNO_PIGHOUSE_FARM = "Farm House"
STRINGS.RECIPE_DESC.KYNO_PIGHOUSE_FARM = "Shelters one farmer pig."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGHOUSE_FARM = "Farm fresh."

STRINGS.NAMES.KYNO_PLAYERHOUSE = "Slanty Shanty"
STRINGS.RECIPE_DESC.KYNO_PLAYERHOUSE = "Build your own house."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PLAYERHOUSE = "Home sweet home."

STRINGS.NAMES.KYNO_PLAYERHOUSE_MANOR = "Manor Shanty"
STRINGS.RECIPE_DESC.KYNO_PLAYERHOUSE_MANOR = "Build your own house."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PLAYERHOUSE_MANOR = "Home sweet home."

STRINGS.NAMES.KYNO_PLAYERHOUSE_VILLA = "Villa Shanty"
STRINGS.RECIPE_DESC.KYNO_PLAYERHOUSE_VILLA = "Build your own house."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PLAYERHOUSE_VILLA = "Home sweet home."

STRINGS.NAMES.KYNO_PLAYERHOUSE_COTTAGE = "Cottage Shanty"
STRINGS.RECIPE_DESC.KYNO_PLAYERHOUSE_COTTAGE = "Build your own house."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PLAYERHOUSE_COTTAGE = "Home sweet home."

STRINGS.NAMES.KYNO_PLAYERHOUSE_TUDOR = "Tudor Shanty"
STRINGS.RECIPE_DESC.KYNO_PLAYERHOUSE_TUDOR = "Build your own house."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PLAYERHOUSE_TUDOR = "Home sweet home."

STRINGS.NAMES.KYNO_PLAYERHOUSE_GOTHIC = "Gothic Shanty"
STRINGS.RECIPE_DESC.KYNO_PLAYERHOUSE_GOTHIC = "Build your own house."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PLAYERHOUSE_GOTHIC = "Home sweet home."

STRINGS.NAMES.KYNO_PLAYERHOUSE_BRICK = "Brick Shanty"
STRINGS.RECIPE_DESC.KYNO_PLAYERHOUSE_BRICK = "Build your own house."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PLAYERHOUSE_BRICK = "Home sweet home."

STRINGS.NAMES.KYNO_PLAYERHOUSE_TURRET = "Turreted Shanty"
STRINGS.RECIPE_DESC.KYNO_PLAYERHOUSE_TURRET = "Build your own house."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PLAYERHOUSE_TURRET = "Home sweet home."

STRINGS.NAMES.KYNO_SMASHINGPOT = "A Smashing Pot"
STRINGS.RECIPE_DESC.KYNO_SMASHINGPOT = "An ancient pot."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SMASHINGPOT = "A pot that appears smashable."

STRINGS.NAMES.KYNO_SMASHEDPOT = "A Smashed Pot"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SMASHEDPOT = "Well. it's broken now."

STRINGS.NAMES.WALL_PIG_RUINS = "Ancient Wall"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_PIG_RUINS = "It's an old wall."

STRINGS.NAMES.WALL_PIG_RUINS_ITEM = "Ancient Wall"
STRINGS.RECIPE_DESC.WALL_PIG_RUINS_ITEM = "Remains of a ancient civilization."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_PIG_RUINS_ITEM = "It's an old wall."

STRINGS.NAMES.KYNO_ANTCOMBHOME = "Antcomb Home"
STRINGS.RECIPE_DESC.KYNO_ANTCOMBHOME = "Mant's Lair."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ANTCOMBHOME = "Looks like it houses insects."

STRINGS.NAMES.KYNO_ANTCHEST = "Honey Chest"
STRINGS.RECIPE_DESC.KYNO_ANTCHEST = "Honey don't spoil inside!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ANTCHEST = "Take its sweet time making honey."

STRINGS.NAMES.KYNO_ANTCACHE = "Honey Cache"
STRINGS.RECIPE_DESC.KYNO_ANTCACHE = "Full of honeycombs."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ANTCACHE = "It's a storage for honey."

STRINGS.NAMES.KYNO_ROCK_ARTICHOKE  = "Artichoke"
STRINGS.RECIPE_DESC.KYNO_ROCK_ARTICHOKE = "A very old boulder."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ROCK_ARTICHOKE = "It's very old."

STRINGS.NAMES.KYNO_APORKALYPSE_CALENDAR = "Aporkalypse Calendar"
STRINGS.RECIPE_DESC.KYNO_APORKALYPSE_CALENDAR = "Control the aporkalypse."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_APORKALYPSE_CALENDAR = "Looks ominous."

STRINGS.NAMES.KYNO_RUINS_HEAD = "Crumbling Visage"
STRINGS.RECIPE_DESC.KYNO_RUINS_HEAD = "An old pig head."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_RUINS_HEAD = "This head is very old."

STRINGS.NAMES.KYNO_RUINS_PIGSTATUE = "Crumbling Visage"
STRINGS.RECIPE_DESC.KYNO_RUINS_PIGSTATUE = "An old pig statue."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_RUINS_PIGSTATUE = "It's a ancient pig stuate."

STRINGS.NAMES.KYNO_RUINS_ANTSTATUE = "Crumbling Visage"
STRINGS.RECIPE_DESC.KYNO_RUINS_ANTSTATUE = "An old mant statue."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_RUINS_ANTSTATUE = "It's a mant stuate."

STRINGS.NAMES.KYNO_RUINS_IDOLSTATUE = "Tempting Idol"
STRINGS.RECIPE_DESC.KYNO_RUINS_IDOLSTATUE = "An old pig idol."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_RUINS_IDOLSTATUE = "It's a ancient pig idol."

STRINGS.NAMES.KYNO_RUINS_PLAQUESTATUE = "Eroding Totem"
STRINGS.RECIPE_DESC.KYNO_RUINS_PLAQUESTATUE = "An old totem."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_RUINS_PLAQUESTATUE = "It's a ancient totem."

STRINGS.NAMES.KYNO_RUINS_TRUFFLESTATUE = "The Jeweled Truffle"
STRINGS.RECIPE_DESC.KYNO_RUINS_TRUFFLESTATUE = "An old truffle statue."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_RUINS_TRUFFLESTATUE = "It seems like a mushroom to me."

STRINGS.NAMES.KYNO_RUINS_SOWSTATUE = "The Blue Sow"
STRINGS.RECIPE_DESC.KYNO_RUINS_SOWSTATUE = "An old blue pig statue."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_RUINS_SOWSTATUE = "It seems like a piglet to me."

STRINGS.NAMES.KYNO_WISHINGWELL = "Wishing Well"
STRINGS.RECIPE_DESC.KYNO_WISHINGWELL = "Toss a coin to your wishing well."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WISHINGWELL = "What are the probabilities of this working?"

STRINGS.NAMES.KYNO_ENDWELL = "End's Well"
STRINGS.RECIPE_DESC.KYNO_ENDWELL = "Toss a gem to your end's well."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ENDWELL = "There's something different about this well."

STRINGS.NAMES.KYNO_STRIKINGSTATUE = "Striking Statue"
STRINGS.RECIPE_DESC.KYNO_STRIKINGSTATUE = "Shoot darts."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_STRIKINGSTATUE = "I have a feeling that's a trap."

STRINGS.NAMES.KYNO_SPEARTRAP = "Nasty Spear Trap"
STRINGS.RECIPE_DESC.KYNO_SPEARTRAP = "Traps everywhere!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SPEARTRAP = "I'd be wise to avoid those."

STRINGS.NAMES.KYNO_TEETERINGPILLAR = "Teetering Pillar"
STRINGS.RECIPE_DESC.KYNO_TEETERINGPILLAR = "Support pillar of the fountain."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TEETERINGPILLAR = "It's here since the construction of that fountain."

STRINGS.NAMES.KYNO_TEETERINGPILLAR_COLLAPSED = "Teetering Pillar"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TEETERINGPILLAR_COLLAPSED = "Well. it's gone now."

STRINGS.NAMES.KYNO_PILLAR_FRONT = "Unimportant Pillar"
STRINGS.RECIPE_DESC.KYNO_PILLAR_FRONT = "Pillar of an ancient ruins."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PILLAR_FRONT = "It's still working!"

STRINGS.NAMES.KYNO_PILLAR_FRONT_BROKEN = "Unimportant Pillar"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PILLAR_FRONT_BROKEN = "Well. it's gone now."

STRINGS.NAMES.KYNO_PILLAR_FRONT_BLUE = "Unimportant Blue Pillar"
STRINGS.RECIPE_DESC.KYNO_PILLAR_FRONT_BLUE = "Blue pillar of an ancient ruins."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PILLAR_FRONT_BLUE = "It's still working!"

STRINGS.NAMES.KYNO_PILLAR_FRONT_BLUE_BROKEN = "Unimportant Blue Pillar"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PILLAR_FRONT_BLUE_BROKEN = "Well. it's gone now."

STRINGS.NAMES.KYNO_PUGALISKFOUNTAIN = "Fountain of Youth"
STRINGS.RECIPE_DESC.KYNO_PUGALISKFOUNTAIN = "Live forever."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PUGALISKFOUNTAIN = "I'll live forever!"

STRINGS.NAMES.KYNO_TRAPDOOR = "Ominous Carving"
STRINGS.RECIPE_DESC.KYNO_TRAPDOOR = "Free the snake."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TRAPDOOR = "Is that snake in there?"

STRINGS.NAMES.KYNO_PUGALISKCORPSE = "Petrifying Bones"
STRINGS.RECIPE_DESC.KYNO_PUGALISKCORPSE = "Mortal remains of a giant snake."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PUGALISKCORPSE = "Life is fragile. Even for evil snakes."

STRINGS.NAMES.KYNO_EXOTICFLOWER = "Exotic Flower"
STRINGS.RECIPE_DESC.KYNO_EXOTICFLOWER = "A tropical flower."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_EXOTICFLOWER = "This flower is different."

STRINGS.NAMES.KYNO_ROCK_ERUPTION = "Basalt Eruption"
STRINGS.RECIPE_DESC.KYNO_ROCK_ERUPTION = "Made of magma and basalt."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ROCK_ERUPTION = "A rock infused with other rocks."

STRINGS.NAMES.KYNO_BRAZIER = "Crumbling Brazier"
STRINGS.RECIPE_DESC.KYNO_BRAZIER = "A ancient pig torch."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BRAZIER = "It's an ancient pig fire brazier."

STRINGS.NAMES.KYNO_BALLOON_WRECK = "Deflated Balloon"
STRINGS.RECIPE_DESC.KYNO_BALLOON_WRECK = "Remains of a balloon."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BALLOON_WRECK = "There go all my dreams."

STRINGS.NAMES.KYNO_BASKET_WRECK = "Wicker Basket"
STRINGS.RECIPE_DESC.KYNO_BASKET_WRECK = "Remains of a basket."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BASKET_WRECK = "A complete basket case."

STRINGS.NAMES.KYNO_SANDBAG_WRECK = "Bag of Sand"
STRINGS.RECIPE_DESC.KYNO_SANDBAG_WRECK = "Remains of a sand bag."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SANDBAG_WRECK = "It's been sandbagged."

STRINGS.NAMES.KYNO_FLAGS_WRECK = "Useless Flags"
STRINGS.RECIPE_DESC.KYNO_FLAGS_WRECK = "Remains of a flag."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_FLAGS_WRECK = "I guess it raised some red flags."

STRINGS.NAMES.KYNO_SUITCASE_WRECK = "Mongrammed Luggage"
STRINGS.RECIPE_DESC.KYNO_SUITCASE_WRECK = "Remains of a luggage."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SUITCASE_WRECK = "Well it has a 'W' on it so it must be mine."

STRINGS.NAMES.KYNO_TRUNK_WRECK = "Mongrammed Luggage"
STRINGS.RECIPE_DESC.KYNO_TRUNK_WRECK = "Remains of a luggage."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TRUNK_WRECK = "Well it has a 'W' on it so it must be mine."

STRINGS.NAMES.KYNO_DUNGBALL = "Dung Ball"
STRINGS.RECIPE_DESC.KYNO_DUNGBALL = "A ball of poop."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_DUNGBALL = "Most definitely poop."

STRINGS.NAMES.KYNO_DUNGPILE = "Dung Pile"
STRINGS.RECIPE_DESC.KYNO_DUNGPILE = "A pile of poop."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_DUNGPILE = "It's a pile of poop..."

STRINGS.NAMES.KYNO_GNATMOUND = "Gnat Mound"
STRINGS.RECIPE_DESC.KYNO_GNATMOUND = "Aedes aegypti's lair."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_GNATMOUND = "Ugh. The horde home."

STRINGS.NAMES.KYNO_MANDRAKEHOUSE = "Mandrake Hill"
STRINGS.RECIPE_DESC.KYNO_MANDRAKEHOUSE = "A house for magical plants."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MANDRAKEHOUSE = "It's where those little plant guys live."

STRINGS.NAMES.KYNO_BANDITTREASURE = "Secret Bandit Camp"
STRINGS.RECIPE_DESC.KYNO_BANDITTREASURE = "It's a secret to everyone."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BANDITTREASURE = "Treasure!"

STRINGS.NAMES.KYNO_SPARKPOOL = "Sparkling Pool"
STRINGS.RECIPE_DESC.KYNO_SPARKPOOL = "Filled with gold."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SPARKPOOL = "Pool's gold."

STRINGS.NAMES.KYNO_BATHOLE = "Spooky Hole"
STRINGS.RECIPE_DESC.KYNO_BATHOLE = "Vampire bat's den."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BATHOLE = "Smells like a million giant bats."

STRINGS.NAMES.KYNO_BATPIT = "Dangerous Pit"
STRINGS.RECIPE_DESC.KYNO_BATPIT = "It's full of bats."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BATPIT = "Full of bats."

STRINGS.NAMES.KYNO_ANTTHRONE = "Stalacmite Throne"
STRINGS.RECIPE_DESC.KYNO_ANTTHRONE = "A giant throne made of stone."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ANTTHRONE = "I should break that."

STRINGS.NAMES.KYNO_ROCK_PLUG = "Stone Plug"
STRINGS.RECIPE_DESC.KYNO_ROCK_PLUG = "It's plugged."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ROCK_PLUG = "It's a strange rock formation."

STRINGS.NAMES.KYNO_STONESLAB = "Stone Slab"
STRINGS.RECIPE_DESC.KYNO_STONESLAB = "Flip the stone!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_STONESLAB = "You never know what you'll find under a rock."

STRINGS.NAMES.KYNO_THUNDERNEST = "Thundernest"
STRINGS.RECIPE_DESC.KYNO_THUNDERNEST = "It's charged!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_THUNDERNEST = "A bird nest."

STRINGS.NAMES.KYNO_ROCNEST = "BFB's Nest"
STRINGS.RECIPE_DESC.KYNO_ROCNEST = "A huge bird nest."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ROCNEST = "I wonder what kind of bird lives here."

STRINGS.NAMES.KYNO_NEST_EGG1 = "Petrified Egg"
STRINGS.RECIPE_DESC.KYNO_NEST_EGG1 = "A petrified bird egg."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_NEST_EGG1 = "Eggshell-ent."

STRINGS.NAMES.KYNO_NEST_EGG2 = "Petrified Egg"
STRINGS.RECIPE_DESC.KYNO_NEST_EGG2 = "A petrified bird egg."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_NEST_EGG2 = "Eggshell-ent."

STRINGS.NAMES.KYNO_NEST_EGG3 = "Petrified Egg"
STRINGS.RECIPE_DESC.KYNO_NEST_EGG3 = "A petrified bird egg."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_NEST_EGG3 = "Eggshell-ent."

STRINGS.NAMES.KYNO_NEST_EGG4 = "Petrified Egg"
STRINGS.RECIPE_DESC.KYNO_NEST_EGG4 = "A petrified bird egg."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_NEST_EGG4 = "Eggshell-ent."

STRINGS.NAMES.KYNO_NEST_TREE1 = "Weathered Tree"
STRINGS.RECIPE_DESC.KYNO_NEST_TREE1 = "A weathered pink tree."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_NEST_TREE1 = "Looks like it's been transplanted here."

STRINGS.NAMES.KYNO_NEST_TREE2 = "Weathered Tree"
STRINGS.RECIPE_DESC.KYNO_NEST_TREE2 = "A weathered pink tree."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_NEST_TREE2 = "Looks like it's been transplanted here."

STRINGS.NAMES.KYNO_NEST_BUSH = "Weathered Shrub"
STRINGS.RECIPE_DESC.KYNO_NEST_BUSH = "A weathered pink shrub."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_NEST_BUSH = "Pity there are no berries on it."

STRINGS.NAMES.KYNO_NEST_BRANCH1 = "Weathered Branch"
STRINGS.RECIPE_DESC.KYNO_NEST_BRANCH1 = "A weathered tree branch."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_NEST_BRANCH1 = "Just a branch."

STRINGS.NAMES.KYNO_NEST_BRANCH2 = "Weathered Branch"
STRINGS.RECIPE_DESC.KYNO_NEST_BRANCH2 = "A weathered tree branch."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_NEST_BRANCH2 = "Just a branch."

STRINGS.NAMES.KYNO_NEST_TRUNK = "Weathered Trunk"
STRINGS.RECIPE_DESC.KYNO_NEST_TRUNK = "A weathered trunk."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_NEST_TRUNK = "What could've broken that?"

STRINGS.NAMES.KYNO_NEST_HOUSE = "Weathered House"
STRINGS.RECIPE_DESC.KYNO_NEST_HOUSE = "A weathered house."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_NEST_HOUSE = "An empty house."

STRINGS.NAMES.KYNO_NEST_RUSTY_LAMP = "Rusty Lamp"
STRINGS.RECIPE_DESC.KYNO_NEST_RUSTY_LAMP = "A broken lamp."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_NEST_RUSTY_LAMP = "Busted and rusted."

STRINGS.NAMES.KYNO_NEST_DEBRIS1 = "Weathered Stick"
STRINGS.RECIPE_DESC.KYNO_NEST_DEBRIS1 = "A weathered stick."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_NEST_DEBRIS1 = "It's a stick."

STRINGS.NAMES.KYNO_NEST_DEBRIS2 = "Weathered Stick"
STRINGS.RECIPE_DESC.KYNO_NEST_DEBRIS2 = "A weathered stick."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_NEST_DEBRIS2 = "It's a stick."

STRINGS.NAMES.KYNO_NEST_DEBRIS3 = "Weathered Stick"
STRINGS.RECIPE_DESC.KYNO_NEST_DEBRIS3 = "A weathered stick."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_NEST_DEBRIS3 = "It's a stick."

STRINGS.NAMES.KYNO_NEST_DEBRIS4 = "Weathered Stick"
STRINGS.RECIPE_DESC.KYNO_NEST_DEBRIS4 = "A weathered stick."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_NEST_DEBRIS4 = "It's a stick."

STRINGS.NAMES.KYNO_IRONHULK_SPIDER = "Iron Hulk"
STRINGS.RECIPE_DESC.KYNO_IRONHULK_SPIDER = "An old automation."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_IRONHULK_SPIDER = "All that gear should be mine."

STRINGS.NAMES.KYNO_IRONHULK_LEG = "Iron Hulk"
STRINGS.RECIPE_DESC.KYNO_IRONHULK_LEG = "An old automation."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_IRONHULK_LEG = "Not a leg to stand on."

STRINGS.NAMES.KYNO_IRONHULK_HEAD = "Iron Hulk"
STRINGS.RECIPE_DESC.KYNO_IRONHULK_HEAD = "An old automation."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_IRONHULK_HEAD = "I'm heading out of here!"

STRINGS.NAMES.KYNO_IRONHULK_CLAW = "Iron Hulk"
STRINGS.RECIPE_DESC.KYNO_IRONHULK_CLAW = "An old automation."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_IRONHULK_CLAW = "Careful! it's armed!"

STRINGS.NAMES.KYNO_IRONHULK_LARGE = "Ancient Hulk"
STRINGS.RECIPE_DESC.KYNO_IRONHULK_LARGE = "Iron hulks assembly!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_IRONHULK_LARGE = "It must be using some sort of ancient technology!"

STRINGS.NAMES.KYNO_BRAMBLE1 = "Bramble"
STRINGS.RECIPE_DESC.KYNO_BRAMBLE1 = "Spikes everywhere!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BRAMBLE1 = "An overly complicated spiky thing."

STRINGS.NAMES.KYNO_BRAMBLE2 = "Bramble"
STRINGS.RECIPE_DESC.KYNO_BRAMBLE2 = "Spikes everywhere!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BRAMBLE2 = "An overly complicated spiky thing."

STRINGS.NAMES.KYNO_BRAMBLE3 = "Bramble"
STRINGS.RECIPE_DESC.KYNO_BRAMBLE3 = "Spikes everywhere!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BRAMBLE3 = "An overly complicated spiky thing."

STRINGS.NAMES.KYNO_BRAMBLECORE = "Bramble Bloom"
STRINGS.RECIPE_DESC.KYNO_BRAMBLECORE = "Heart of the brambles."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BRAMBLECORE = "It's pretty, but is it worth the trouble?"

STRINGS.NAMES.CLAWTREE = "Claw Palm Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CLAWTREE = "That's some weird wood."

STRINGS.NAMES.KYNO_CLAWTREE_SAPLING = "Claw Palm Tree Sapling"
STRINGS.RECIPE_DESC.KYNO_CLAWTREE_SAPLING = "It's a wonder how this things grow."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CLAWTREE_SAPLING = "Require quite a bit of care."

STRINGS.NAMES.CLAWTREE_SHORT = "Claw Palm Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CLAWTREE_SHORT = "That's some weird wood."

STRINGS.NAMES.CLAWTREE_SHORT = "Claw Palm Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CLAWTREE_SHORT = "That's some weird wood."

STRINGS.NAMES.CLAWTREE_NORMAL = "Claw Palm Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CLAWTREE_NORMAL = "That's some weird wood."

STRINGS.NAMES.CLAWTREE_TALL = "Claw Palm Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CLAWTREE_TALL = "That's some weird wood."

STRINGS.NAMES.CLAWTREE_BURNT = "Claw Palm Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CLAWTREE_BURNT = "That's some weird wood."

STRINGS.NAMES.CLAWTREE_STUMP = "Claw Palm Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CLAWTREE_STUMP = "That's some weird wood."

STRINGS.NAMES.KYNO_ALOE_PLANTED = "Aloe"
STRINGS.RECIPE_DESC.KYNO_ALOE_PLANTED = "Aloe to the ground!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ALOE_PLANTED = "I hear aloe's good for you."

STRINGS.NAMES.KYNO_ASPARAGUS_PLANTED = "Asparagus"
STRINGS.RECIPE_DESC.KYNO_ASPARAGUS_PLANTED = "A planted asparagus."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ASPARAGUS_PLANTED = "A planted vegetable."

STRINGS.NAMES.KYNO_LEAFYSTALK = "Great Leafy Stalk"
STRINGS.RECIPE_DESC.KYNO_LEAFYSTALK = "An ancient giant tree."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_LEAFYSTALK = "It totally blocks out the sun."

STRINGS.NAMES.KYNO_COCOON = "Glowfly Cocoon"
STRINGS.RECIPE_DESC.KYNO_COCOON = "Life cycle of a glowfly."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COCOON = "Ew."

STRINGS.NAMES.KYNO_JUNGLEFERN = "Jungle Fern"
STRINGS.RECIPE_DESC.KYNO_JUNGLEFERN = "A small jungle foliage."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_JUNGLEFERN = "It's a jungle fern."

STRINGS.NAMES.KYNO_JUNGLEFERN_GREEN = "Jungle Fern"
STRINGS.RECIPE_DESC.KYNO_JUNGLEFERN_GREEN = "A small green jungle foliage."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_JUNGLEFERN_GREEN = "It's a jungle fern."

STRINGS.NAMES.KYNO_VINE1 = "Hanging Vine"
STRINGS.RECIPE_DESC.KYNO_VINE1 = "A plant that eat things."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_VINE1 = "Always hanging around."

STRINGS.NAMES.KYNO_VINE2 = "Hanging Vine"
STRINGS.RECIPE_DESC.KYNO_VINE2 = "A hanging vine."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_VINE2 = "Ugh, vines!"

STRINGS.NAMES.HEDGE_BLOCK = "Block Hedge"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HEDGE_BLOCK = "What an excellent topiary!"

STRINGS.NAMES.HEDGE_BLOCK_AGED = "Block Hedge"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HEDGE_BLOCK_AGED = "Needs a hair cut."

STRINGS.NAMES.HEDGE_LAYERED = "Layered Hedge"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HEDGE_LAYERED = "What an excellent topiary!"

STRINGS.NAMES.HEDGE_LAYERED_AGED = "Layered Hedge"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HEDGE_LAYERED_AGED = "Needs a hair cut."

STRINGS.NAMES.HEDGE_CONE = "Cone Hedge"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HEDGE_CONE = "What an excellent topiary!"

STRINGS.NAMES.HEDGE_CONE_AGED = "Cone Hedge"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HEDGE_CONE_AGED = "Needs a hair cut."

STRINGS.NAMES.HEDGE_BLOCK_ITEM = "Block Hedge"
STRINGS.RECIPE_DESC.HEDGE_BLOCK_ITEM = "For squares."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HEDGE_BLOCK_ITEM = "I should place this."

STRINGS.NAMES.HEDGE_BLOCK_AGED_ITEM = "Aged Block Hedge"
STRINGS.RECIPE_DESC.HEDGE_BLOCK_AGED_ITEM = "For a aged squares."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HEDGE_BLOCK_AGED_ITEM = "I should place this."

STRINGS.NAMES.HEDGE_LAYERED_ITEM = "Layered Hedge"
STRINGS.RECIPE_DESC.HEDGE_LAYERED_ITEM = "For variety."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HEDGE_LAYERED_ITEM = "I should place this."

STRINGS.NAMES.HEDGE_LAYERED_AGED_ITEM = "Aged Layered Hedge"
STRINGS.RECIPE_DESC.HEDGE_LAYERED_AGED_ITEM = "For a aged variety."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HEDGE_LAYERED_AGED_ITEM = "I should place this."

STRINGS.NAMES.HEDGE_CONE_ITEM = "Cone Hedge"
STRINGS.RECIPE_DESC.HEDGE_CONE_ITEM = "For difference."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HEDGE_CONE_ITEM = "I should place this."

STRINGS.NAMES.HEDGE_CONE_AGED_ITEM = "Aged Cone Hedge"
STRINGS.RECIPE_DESC.HEDGE_CONE_AGED_ITEM = "For a aged difference."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HEDGE_CONE_AGED_ITEM = "I should place this."

STRINGS.NAMES.KYNO_LAWNORNAMENT_1 = "Layer Tree"
STRINGS.RECIPE_DESC.KYNO_LAWNORNAMENT_1 = "A happy little tree."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_LAWNORNAMENT_1 = "A bit of ornamentation."

STRINGS.NAMES.KYNO_LAWNORNAMENT_2 = "Irregular Tree"
STRINGS.RECIPE_DESC.KYNO_LAWNORNAMENT_2 = "A complex little tree."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_LAWNORNAMENT_2 = "A bit of ornamentation."

STRINGS.NAMES.KYNO_LAWNORNAMENT_3 = "Umbrella Tree"
STRINGS.RECIPE_DESC.KYNO_LAWNORNAMENT_3 = "Does not protect you from rain."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_LAWNORNAMENT_3 = "A bit of ornamentation."

STRINGS.NAMES.KYNO_LAWNORNAMENT_4 = "Floopy Tree"
STRINGS.RECIPE_DESC.KYNO_LAWNORNAMENT_4 = "A bent little tree."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_LAWNORNAMENT_4 = "A bit of ornamentation."

STRINGS.NAMES.KYNO_LAWNORNAMENT_5 = "Funbrella Tree"
STRINGS.RECIPE_DESC.KYNO_LAWNORNAMENT_5 = "Does not protect you from fun."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_LAWNORNAMENT_5 = "A bit of ornamentation."

STRINGS.NAMES.KYNO_LAWNORNAMENT_6 = "Flowering Tree"
STRINGS.RECIPE_DESC.KYNO_LAWNORNAMENT_6 = "The pot is plastic."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_LAWNORNAMENT_6 = "A bit of ornamentation."

STRINGS.NAMES.KYNO_LAWNORNAMENT_7 = "Spiral Tree"
STRINGS.RECIPE_DESC.KYNO_LAWNORNAMENT_7 = "The tree is plastic."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_LAWNORNAMENT_7 = "A bit of ornamentation."

STRINGS.NAMES.KYNO_TOPIARY_1 = "Intricate Topiary"
STRINGS.RECIPE_DESC.KYNO_TOPIARY_1 = "A pig for ornamentation."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TOPIARY_1 = "To think the artist had only hoofs to work with."

STRINGS.NAMES.KYNO_TOPIARY_2 = "Intricate Topiary"
STRINGS.RECIPE_DESC.KYNO_TOPIARY_2 = "A werepig for ornamentation."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TOPIARY_2 = "To think the artist had only hoofs to work with."

STRINGS.NAMES.KYNO_TOPIARY_3 = "Intricate Topiary"
STRINGS.RECIPE_DESC.KYNO_TOPIARY_3 = "A beefalo for ornamentation."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TOPIARY_3 = "To think the artist had only hoofs to work with."

STRINGS.NAMES.KYNO_TOPIARY_4 = "Intricate Topiary"
STRINGS.RECIPE_DESC.KYNO_TOPIARY_4 = "A pig king for ornamentation."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TOPIARY_4 = "To think the artist had only hoofs to work with."

STRINGS.NAMES.KYNO_MAGICFLOWER = "Magic Flower"
STRINGS.RECIPE_DESC.KYNO_MAGICFLOWER = "Full of magic."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MAGICFLOWER = "It's a magic flower!"

STRINGS.NAMES.KYNO_NETTLEPLANT = "Nettle Vine"
STRINGS.RECIPE_DESC.KYNO_NETTLEPLANT = "An exotic plant."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_NETTLEPLANT = "This plant's strong odor clears my sinuses."

STRINGS.NAMES.KYNO_TALLGRASS = "Tall Grass"
STRINGS.RECIPE_DESC.KYNO_TALLGRASS = "This grass is uncommon."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TALLGRASS = "What? It's super tall!"

STRINGS.NAMES.KYNO_CORKCHEST = "Cork Barrel"
STRINGS.RECIPE_DESC.KYNO_CORKCHEST = "Fill and put a cork in it."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CORKCHEST = "A pest protector."

STRINGS.NAMES.KYNO_HOGUSPORKUSATOR = "Hogus Porkusator"
STRINGS.RECIPE_DESC.KYNO_HOGUSPORKUSATOR = "Pigs can do tricks too."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_HOGUSPORKUSATOR = "Pig Magic!"

STRINGS.NAMES.KYNO_ROOTCHEST = "Root Trunk"
STRINGS.RECIPE_DESC.KYNO_ROOTCHEST = "Pass things along the grape vine."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ROOTCHEST = "It rooted out all my things!"

STRINGS.NAMES.KYNO_SPRINKLER = "Sprinkler"
STRINGS.RECIPE_DESC.KYNO_SPRINKLER = "Waters plants."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SPRINKLER = "Water you think it's for?"

STRINGS.NAMES.KYNO_SMELTER = "Smelter"
STRINGS.RECIPE_DESC.KYNO_SMELTER = "Turn iron into alloy!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SMELTER = "I smelt that!"

STRINGS.NAMES.KYNO_BASEFAN = "Oscillating Fan"
STRINGS.RECIPE_DESC.KYNO_BASEFAN = "Relieves Wigfever, keeps you dry."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BASEFAN = "Fan-tastic."

STRINGS.NAMES.KYNO_THUMPER = "Thumper"
STRINGS.RECIPE_DESC.KYNO_THUMPER = "A revolutionary harvester."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_THUMPER = "Does all the hard work for me."

STRINGS.NAMES.KYNO_TELIPAD = "Telipad"
STRINGS.RECIPE_DESC.KYNO_TELIPAD = "A revolutionary platform."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TELIPAD = "A landing pad for jumping through space."

STRINGS.NAMES.TUBERTREE = "Tuber Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUBERTREE = "Totally tubular."

STRINGS.NAMES.TUBERTREE_SHORT = "Tuber Tree"
STRINGS.RECIPE_DESC.TUBERTREE_SHORT = "A peculiar tubular tree."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUBERTREE_SHORT = "Totally tubular."

STRINGS.NAMES.TUBERTREE_TALL = "Tuber Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUBERTREE_TALL = "Totally tubular."

STRINGS.NAMES.TUBERTREE_BURNT = "Tuber Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUBERTREE_BURNT = "Totally tubular."

STRINGS.NAMES.TUBERTREE_STUMP = "Tuber Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUBERTREE_STUMP = "Totally tubular."

STRINGS.NAMES.TUBERTREEBLOOM = "Tuber Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUBERTREEBLOOM = "It's blooming."

STRINGS.NAMES.TUBERTREEBLOOM_SHORT = "Tuber Tree"
STRINGS.RECIPE_DESC.TUBERTREEBLOOM_SHORT = "A peculiar blooming tubular tree."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUBERTREEBLOOM_SHORT = "It's blooming."

STRINGS.NAMES.TUBERTREEBLOOM_TALL = "Tuber Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUBERTREEBLOOM_TALL = "It's blooming."

STRINGS.NAMES.TUBERTREEBLOOM_BURNT = "Tuber Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUBERTREEBLOOM_BURNT = "It's blooming."

STRINGS.NAMES.TUBERTREEBLOOM_STUMP = "Tuber Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUBERTREEBLOOM_STUMP = "It's Blooming."

STRINGS.NAMES.BURR = "Jungle Burr"
STRINGS.RECIPE_DESC.BURR = "Rainy tree seed."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BURR = "A tiny seed inside."

STRINGS.NAMES.KYNO_RAINFORESTTREE_SAPLING = "Rainforest Tree Sapling"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_RAINFORESTTREE_SAPLING = "It's growing."

STRINGS.NAMES.RAINFORESTTREE = "Rainforest Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINFORESTTREE = "A tropical tree."

STRINGS.NAMES.RAINFORESTTREE_SHORT = "Rainforest Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINFORESTTREE_SHORT = "A tropical tree."

STRINGS.NAMES.RAINFORESTTREE_NORMAL = "Rainforest Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINFORESTTREE_NORMAL = "A tropical tree."

STRINGS.NAMES.RAINFORESTTREE_TALL = "Rainforest Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINFORESTTREE_TALL = "A tropical tree."

STRINGS.NAMES.RAINFORESTTREE_BURNT = "Rainforest Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINFORESTTREE_BURNT = "A tropical tree."

STRINGS.NAMES.RAINFORESTTREE_STUMP = "Rainforest Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINFORESTTREE_STUMP = "A tropical tree."

STRINGS.NAMES.RAINFORESTTREE_ROT = "Sick Rainforest Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINFORESTTREE_ROT = "Consumed by some kind of sickness."

STRINGS.NAMES.RAINFORESTTREE_ROT_SHORT = "Sick Rainforest Tree"
STRINGS.RECIPE_DESC.RAINFORESTTREE_ROT_SHORT = "A sick tropical tree."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINFORESTTREE_ROT_SHORT = "Consumed by some kind of sickness."

STRINGS.NAMES.RAINFORESTTREE_ROT_NORMAL = "Sick Rainforest Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINFORESTTREE_ROT_NORMAL = "Consumed by some kind of sickness."

STRINGS.NAMES.RAINFORESTTREE_ROT_TALL = "Sick Rainforest Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINFORESTTREE_ROT_TALL = "Consumed by some kind of sickness."

STRINGS.NAMES.RAINFORESTTREE_ROT_BURNT = "Sick Rainforest Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINFORESTTREE_ROT_BURNT = "Consumed by some kind of sickness."

STRINGS.NAMES.RAINFORESTTREE_ROT_STUMP = "Sick Rainforest Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINFORESTTREE_ROT_STUMP = "Consumed by some kind of sickness."

STRINGS.NAMES.RAINFORESTTREE_BLOOM = "Rainforest Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINFORESTTREE_BLOOM = "It's blooming."

STRINGS.NAMES.RAINFORESTTREE_BLOOM_SHORT = "Rainforest Tree"
STRINGS.RECIPE_DESC.RAINFORESTTREE_BLOOM_SHORT = "A blooming tropical tree."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINFORESTTREE_BLOOM_SHORT = "It's blooming."

STRINGS.NAMES.RAINFORESTTREE_BLOOM_NORMAL = "Rainforest Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINFORESTTREE_BLOOM_NORMAL = "It's blooming."

STRINGS.NAMES.RAINFORESTTREE_BLOOM_TALL = "Rainforest Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINFORESTTREE_BLOOM_TALL = "It's blooming."

STRINGS.NAMES.RAINFORESTTREE_BLOOM_BURNT = "Rainforest Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINFORESTTREE_BLOOM_BURNT = "It's blooming."

STRINGS.NAMES.RAINFORESTTREE_BLOOM_STUMP = "Rainforest Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAINFORESTTREE_BLOOM_STUMP = "It's blooming."

STRINGS.NAMES.COCOONEDTREE = "Cocooned Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCOONEDTREE = "It's covered with silk!"

STRINGS.NAMES.COCOONEDTREE_SHORT = "Cocooned Tree"
STRINGS.RECIPE_DESC.COCOONEDTREE_SHORT = "A tropical tree covered with silk."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCOONEDTREE_SHORT = "It's covered with silk!"

STRINGS.NAMES.COCOONEDTREE_NORMAL = "Cocooned Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCOONEDTREE_NORMAL = "It's covered with silk!"

STRINGS.NAMES.COCOONEDTREE_TALL = "Cocooned Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCOONEDTREE_TALL = "It's covered with silk!"

STRINGS.NAMES.COCOONEDTREE_BURNT = "Cocooned Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCOONEDTREE_BURNT = "It's covered with silk!"

STRINGS.NAMES.COCOONEDTREE_STUMP = "Cocooned Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCOONEDTREE_STUMP = "It's covered with silk!"

STRINGS.NAMES.KYNO_LAMPPOST = "Lamp Post"
STRINGS.RECIPE_DESC.KYNO_LAMPPOST = "I can't believe I can make this."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_LAMPPOST = "When you're lost in the darkness, look for the light."

STRINGS.NAMES.KYNO_TEATREE_SAPLING = "Tea Tree Sapling"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TEATREE_SAPLING = "It's gonna be a tea tree soon."

STRINGS.NAMES.TEATREE_NUT = "Seed Pod"
STRINGS.RECIPE_DESC.TEATREE_NUT = "Grow your own tea forest."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEATREE_NUT = "Stops the seasonal sneezing."

STRINGS.NAMES.TEATREE = "Tea Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEATREE = "What a lovely tree."

STRINGS.NAMES.TEATREE_SHORT = "Tea Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEATREE_SHORT = "What a lovely tree."

STRINGS.NAMES.TEATREE_NORMAL = "Tea Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEATREE_NORMAL = "What a lovely tree."

STRINGS.NAMES.TEATREE_TALL = "Tea Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEATREE_TALL = "What a lovely tree."

STRINGS.NAMES.TEATREE_STUMP = "Tea Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEATREE_STUMP = "What a lovely tree."

STRINGS.NAMES.TEATREE_BURNT = "Tea Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEATREE_BURNT = "What a lovely tree."

STRINGS.NAMES.TURF_COBBLEROAD = "Stone Road Turf"
STRINGS.RECIPE_DESC.TURF_COBBLEROAD = "The life of a thriving village."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_COBBLEROAD = "Some nicely cobbled together rocks."

STRINGS.NAMES.TURF_LAWN = "Lawn Turf"
STRINGS.RECIPE_DESC.TURF_LAWN = "Fully tamed grass."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_LAWN = "It's similar to the carpet one."

STRINGS.NAMES.TURF_FOUNDATION = "Flat Stone Turf"
STRINGS.RECIPE_DESC.TURF_FOUNDATION = "The foundation of a solid village."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_FOUNDATION = "Calling Glermz a rock is not an insult."

STRINGS.NAMES.TURF_FIELDS = "Cultivated Turf"
STRINGS.RECIPE_DESC.TURF_FIELDS = "A civilized patch of dirt."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_FIELDS = "It's good for planting things!"

STRINGS.NAMES.TURF_RAINFOREST = "Rainforest Turf"
STRINGS.RECIPE_DESC.TURF_RAINFOREST = "A tropical turf."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_RAINFOREST = "I can hear the sound of the jungle."

STRINGS.NAMES.TURF_PLAINS = "Wild Plains Turf"
STRINGS.RECIPE_DESC.TURF_PLAINS = "Wild as it can be."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_PLAINS = "So wild."

STRINGS.NAMES.TURF_PIGRUINS = "Ancient Ruins Turf"
STRINGS.RECIPE_DESC.TURF_PIGRUINS = "An ancient stone turf."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_PIGRUINS = "It's from an ancient pig civilization."

STRINGS.NAMES.TURF_DEEPJUNGLE = "Dense Turf"
STRINGS.RECIPE_DESC.TURF_DEEPJUNGLE = "As tame as wild jungle can be."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_DEEPJUNGLE = "I can hear the sound of the deep jungle."

STRINGS.NAMES.TURF_BOG = "Painted Sand Turf"
STRINGS.RECIPE_DESC.TURF_BOG = "Painted sand for ornamentation."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_BOG = "It's painted."

STRINGS.NAMES.TURF_MOSSY_BLOSSOM = "Mossy Turf"
STRINGS.RECIPE_DESC.TURF_MOSSY_BLOSSOM = "Perfect for planting things."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_MOSSY_BLOSSOM = "Ugh, it's covered with moss."

STRINGS.NAMES.TURF_GASJUNGLE = "Toxic Rainforest Turf"
STRINGS.RECIPE_DESC.TURF_GASJUNGLE = "There is a deadly venom on it."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_GASJUNGLE = "Cough! Cough!"

STRINGS.NAMES.TURF_BEARD_HAIR = "Beard Hair Rug"
STRINGS.RECIPE_DESC.TURF_BEARD_HAIR = "Some people just like to do art."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_BEARD_HAIR = "Gross."

STRINGS.NAMES.KYNO_RADISH_PLANTED = "Radish"
STRINGS.RECIPE_DESC.KYNO_RADISH_PLANTED = "A planted radish."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_RADISH_PLANTED = "It looks radishing."

STRINGS.NAMES.KYNO_GRUB = "Giant Grub"
STRINGS.RECIPE_DESC.KYNO_GRUB = "Underground friend!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_GRUB = "It's a giant worm!"

STRINGS.NAMES.KYNO_FAKECOFFEEBUSH = "Coffee Plant"
STRINGS.RECIPE_DESC.KYNO_FAKECOFFEEBUSH = "Coffee Baby?"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_FAKECOFFEEBUSH = "I bet it's fake."

STRINGS.NAMES.KYNO_FLYTRAP = "Snaptooth Flytrap"
STRINGS.RECIPE_DESC.KYNO_FLYTRAP = "A plant friend!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_FLYTRAP = "Science could not have done this."

STRINGS.NAMES.KYNO_DOYDOY = "Doydoy"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_DOYDOY = "I feel oddly protective of this dumb bird."

STRINGS.NAMES.KYNO_GORGE_PROTOTYPER = "The Altar of Gnaw"
STRINGS.RECIPE_DESC.KYNO_GORGE_PROTOTYPER = "Make a snackfrice."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_GORGE_PROTOTYPER = "We'd better start cooking some offerings."

STRINGS.NAMES.KYNO_BOLLARD = "Post"
STRINGS.RECIPE_DESC.KYNO_BOLLARD = "A little post."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BOLLARD = "It's made out of stone, pretty!"